### ISSUE TITLE
Multiple objects

### ISSUE THREAD

**Issue by benedsmith** [benedsmith/PyTextBox#1]
More than one textbox causes issues with typing, selecting and displaying text. 
Boxes do not seem to be acting as individuals.

**Comment by Evolution0** [comment]
Just throwing this out there but have you tried creating another class that inherits `TextBox` and putting the actual text, color, position, etc there?

Because `TextBox` is a type of text box, not a text box itself, you should be creating instances of actual text boxes that just inherit it.

**Comment by benedsmith** [comment]
Issue has been fixed by changing the text data to a string 
See:
https://github.com/benedsmith/PyTextBox/commit/75e972759a5fa33b4230090ed9bd880fbc456243
